### ISSUE TITLE
Full URLs are not supported

### ISSUE THREAD

**Issue by vpetro** [sbt/sbt-giter8-resolver#1]
Giter8 supports the use of full URLs to load a template. However, the `sbt new` command does not provide the same support. 

Example:

```
~  λ sbt new https://github.com/eed3si9n/hello.g8
[info] Loading global plugins from /Users/petrov/.sbt/0.13/plugins
[info] Updating {file:/Users/petrov/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/petrov/.sbt/0.13/plugins/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to petrov (in build file:/Users/petrov/)
Template not found for: https://github.com/eed3si9n/hello.g8
```

```
~  λ g8 https://github.com/eed3si9n/hello.g8
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
name [hello]:
```

**Comment by eed3si9n** [comment]
Fixed in #2

**Comment by m-yamaguchi** [comment]
This issue is not yet fixed.
Pattern match in `Giter8TemplateResolver` is incorrect.
`args.headOption` returns an `Option[String]`.
So, the following change is needed.

`case GitUrl(uri)` --> `case Some(GitUrl(uri))`

**Comment by dwijnand** [comment]
You're right.
